---
title: Programme
---

### Algorithmique

Le concept de méthode algorithmique est introduit ; de nouveaux exemples seront vus en
terminale. Quelques algorithmes classiques sont étudiés. L’étude de leurs coûts respectifs
prend tout son sens dans le cas de données nombreuses, qui peuvent être
préférentiellement des données ouvertes.

Il est nécessaire de montrer l’intérêt de prouver la correction d’un algorithme pour lequel on
dispose d’une spécification précise, notamment en mobilisant la notion d’invariant sur des
exemples simples. La nécessité de prouver la terminaison d’un programme est mise en
évidence dès qu’on utilise une boucle non bornée (ou, en terminale, des fonctions
récursives) grâce à la mobilisation de la notion de variant sur des exemples simples. 

| **Contenus** | **Capacités attendues** | **Commentaires** |
| --- | --- | --- |
|Algorithmes gloutons|Résoudre un problème grâce à un algorithme glouton|Exemples : problèmes du sac à dos ou du rendu de monnaie. Les algorithmes gloutons constituent une méthode algorithmique parmi d’autres qui seront vues en terminale|
