---
title: Exercices - Variables, affectations et chaînes de caractères
---

_Les exercices précédés du symbole {{< fa desktop >}} sont à faire sur machine, en sauvegardant le fichier si nécessaire._

_Les exercices précédés du symbole {{< fa solid pencil-alt >}} doivent être résolus par écrit._

## {{< fa desktop >}} Exercice 1

Dans la console interactive Python, taper successivement les commandes suivantes :

```{.python code-line-numbers="true"}
a, b, c = 3, 2.5, "toto"
print(a)
print(b)
print(c)
print(type(a))
print(type(b))
print(type(c))
```

Expliquer les résultats obtenus.

--------

## {{< fa solid pencil-alt >}} Exercice 2

On considère le script suivant :

```{.python code-line-numbers="true"}
a = 50
b = 30
a = b + 10
b = a * 2
a = b
b = b - 5
```

Compléter le tableau d'état ci-dessous par les valeurs prises par les variables `a` et `b` à chaque étape.

| Etape | `a` | `b` |
| --- | --- | --- |
|1| | |
|2| | |
|3| | |
|4| | |
|5| | |
|6| | |


:::{.callout-tip}

Dans Thonny, on peut utiliser la fenêtre "variables" et le débogueur pour suivre l'évolution des variables au cours de l'exécution d'un programme.
:::

------------------------------------------

## {{< fa solid pencil-alt >}} Exercice 3
Parmi les 8 noms de variables suivants, quels sont ceux qui ne sont pas acceptés par un programme Python (expliquer pourquoi) ?

| | |
| --- | --- |
|prix.de.ma.voiture | un-prix|
|prix_de_ma_voiture|1prix|
|prix de ma voiture|prixen€|
|prixdemavoiture|prix1|

-------------------------------------------

## {{< fa solid pencil-alt >}} Exercice 4
Que va produire l'exécution du programme suivant ?

```py
a = 100
b = 50
a = b
b = a + 10
print(a)
print(b)
```

----------------------------------------------

## {{< fa solid pencil-alt >}} Exercice 5
Que va produire l'exécution du programme suivant ?

```py
a = 100
a = a - 10
a = a * 2
a = a + 50
print(a)
print("a")
```

----------------------------------------------------------

## {{< fa solid pencil-alt >}} Exercice 6
Après les affectations suivantes, quelles sont les valeurs des variables `a` et `b` ?

```py
a = 1
b = a + 5
a = 2 * b + 3
b = 3 * a + 2
a = 2 * b + 3
```

------------------------------------------

## {{< fa solid pencil-alt >}} Exercice 7
Corriger le programme ci-dessous pour qu'il effectue l'action indiquée en commentaires. Deux solutions différentes sont attendues.

```python
# ce programme affiche la somme de a et de b

a = "4"
b="5"
print("La somme de", a, "et de",b,"est égale à", a + b)
```

<!-- idée : faire à chaque fois des fiches de 10 exos environ; sachant qu'on ne les fera pas tous; mais la correction de tous sera disponible. Ainsi les plus rapides seront toujours occupés. Exercices papier crayon (symbole spécial) et exercices sur ordi (symbole spécial) + référence à des exos du manuel -->