---
title: "Exercice : Formulaires"
---

_Les exercices précédés du symbole {{< fa desktop >}} sont à faire sur machine, en sauvegardant le fichier si nécessaire._

_Les exercices précédés du symbole {{< fa solid pencil-alt >}}doivent être résolus par écrit._

## {{< fa solid pencil-alt >}}Exercice (QCM)

1. Parmi les réponses suivantes, que permet d'effectuer la méthode POST du protocole HTTP ?

    - [ ] Réponse A : Définir le style d'une page web
    - [ ] Réponse B : Pirater des données bancaires
    - [ ] Réponse C : Envoyer une page web vers le client
    - [ ] Réponse D : Envoyer les données saisies dans un formulaire HTML vers un serveur

2. Un site internet utilise une requête HTTP avec la méthode POST pour transmettre les données d'un formulaire. Laquelle des affirmations suivantes est incorrecte ?

    - [ ] Réponse A : les données envoyées ne sont pas visibles
    - [ ] Réponse B : il est possible de transmettre des données de type binaire
    - [ ] Réponse C : les données transmises sont cryptées
    - [ ] Réponse D : il n'y a pas de restriction de longueur pour les données transmises

3. Un internaute clique sur un lien qui envoie la requête HTTP suivante à un serveur : http://jaimelaneige.com/ma_planche/traitement.php?nom=Snow&prenom=Jon Que demande cette requête au serveur ?

    - [ ] Réponse A : de renvoyer le fichier traitement.php en identifiant nom et prénom à Snow et Jon
    - [ ] Réponse B : d'exécuter le fichier traitement.php en identifiant nom et prénom à Snow et Jon
    - [ ] Réponse C : d'indiquer si Jon Snow a bien pris son traitement
    - [ ] Réponse D : de renvoyer le fichier traitement.php en affichant prénom et nom : Jon

